// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by: fluttron generate services
// Source: example_weather_contract.dart
// Timestamp: 2026-02-18T09:48:57.274930Z

/// Model class representing weather information.
class WeatherInfo {
  final String city;
  final double temperature;
  final String condition;
  final DateTime timestamp;

  const WeatherInfo({
    required this.city,
    required this.temperature,
    required this.condition,
    required this.timestamp,
  });

  factory WeatherInfo.fromMap(Map<String, dynamic> map) {
    return WeatherInfo(
      city: map['city'] as String,
      temperature: (map['temperature'] as num).toDouble(),
      condition: map['condition'] as String,
      timestamp: DateTime.parse(map['timestamp'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'city': city,
      'temperature': temperature,
      'condition': condition,
      'timestamp': timestamp.toIso8601String(),
    };
  }
}
