// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by: fluttron generate services
// Source: example_weather_contract.dart
// Timestamp: 2026-02-18T09:48:57.274964Z

/// Model class representing a weather forecast.
class WeatherForecast {
  final DateTime date;
  final double high;
  final double low;
  final String condition;

  const WeatherForecast({
    required this.date,
    required this.high,
    required this.low,
    required this.condition,
  });

  factory WeatherForecast.fromMap(Map<String, dynamic> map) {
    return WeatherForecast(
      date: DateTime.parse(map['date'] as String),
      high: (map['high'] as num).toDouble(),
      low: (map['low'] as num).toDouble(),
      condition: map['condition'] as String,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'date': date.toIso8601String(),
      'high': high,
      'low': low,
      'condition': condition,
    };
  }
}
