// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by: fluttron generate services
// Source: example_weather_contract.dart
// Timestamp: 2026-02-18T09:48:57.274879Z

import 'package:fluttron_ui/fluttron_ui.dart';

/// Type-safe client for the weather host service.
class WeatherServiceClient {
  /// Creates a [WeatherServiceClient] with the given [FluttronClient].
  WeatherServiceClient(this._client);

  final FluttronClient _client;

  /// Gets current weather for the given city.
  Future<WeatherInfo> getCurrentWeather(String city) async {
    final result = await _client.invoke(
      'weather.getCurrentWeather',
      {
        'city': city,
      },
    );
    return WeatherInfo.fromMap(Map<String, dynamic>.from(result as Map));
  }

  /// Gets the forecast for the given city.
  /// 
  /// [days] defaults to 5 if not specified.
  Future<List<WeatherForecast>> getForecast(String city, {int days = 5}) async {
    final result = await _client.invoke(
      'weather.getForecast',
      {
        'city': city,
        'days': days,
      },
    );
    return (result as List).map((e) => WeatherForecast.fromMap(Map<String, dynamic>.from(e as Map))).toList();
  }

  /// Checks if the weather API is available.
  Future<bool> isAvailable() async {
    final result = await _client.invoke('weather.isAvailable', {});
    return result['result'] as bool;
  }

}
