import 'dart:io';

import 'package:path/path.dart' as p;

import 'web_package_manifest.dart';

/// Exception thrown when registration code generation fails.
class RegistrationGeneratorException implements Exception {
  RegistrationGeneratorException(this.message);

  final String message;

  @override
  String toString() => message;
}

/// Result of registration code generation.
class RegistrationResult {
  const RegistrationResult({
    required this.outputPath,
    required this.packageCount,
    required this.factoryCount,
    required this.hasGenerated,
  });

  /// Path to the generated Dart file.
  final String outputPath;

  /// Number of web packages processed.
  final int packageCount;

  /// Total number of view factories registered.
  final int factoryCount;

  /// Whether any code was generated (false if no packages).
  final bool hasGenerated;

  @override
  String toString() =>
      'RegistrationResult(outputPath: $outputPath, packageCount: $packageCount, '
      'factoryCount: $factoryCount, hasGenerated: $hasGenerated)';
}

/// Generates view factory registration code for Fluttron web packages.
///
/// This class generates a Dart file with `registerFluttronWebPackages()` function
/// that registers all view factories from discovered web packages using
/// `FluttronWebViewRegistry`.
class RegistrationGenerator {
  /// Default output directory relative to UI project.
  static const String defaultOutputDir = 'lib/generated';

  /// Default output filename.
  static const String defaultOutputFilename = 'web_package_registrations.dart';

  /// Generates registration code from web package manifests.
  ///
  /// [uiProjectDir] - The UI project directory (containing lib/).
  /// [packages] - List of web package manifests to generate registrations for.
  /// [outputDir] - Optional custom output directory (relative to UI project).
  Future<RegistrationResult> generate({
    required Directory uiProjectDir,
    required List<WebPackageManifest> packages,
    String? outputDir,
  }) async {
    final targetDir = p.join(uiProjectDir.path, outputDir ?? defaultOutputDir);
    final outputPath = p.join(targetDir, defaultOutputFilename);
    final outputFile = File(outputPath);
    final factoryCount = _countFactories(packages);

    // Ensure output directory exists
    final dir = Directory(targetDir);
    if (!dir.existsSync()) {
      await dir.create(recursive: true);
    }

    // Generate content
    final content = factoryCount == 0
        ? _generateEmptyContent()
        : _generateCodeContent(packages);

    // Write file
    await outputFile.writeAsString(content);

    return RegistrationResult(
      outputPath: outputPath,
      packageCount: packages.length,
      factoryCount: factoryCount,
      hasGenerated: factoryCount > 0,
    );
  }

  /// Synchronous version of [generate].
  RegistrationResult generateSync({
    required Directory uiProjectDir,
    required List<WebPackageManifest> packages,
    String? outputDir,
  }) {
    final targetDir = p.join(uiProjectDir.path, outputDir ?? defaultOutputDir);
    final outputPath = p.join(targetDir, defaultOutputFilename);
    final outputFile = File(outputPath);
    final factoryCount = _countFactories(packages);

    // Ensure output directory exists
    final dir = Directory(targetDir);
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    // Generate content
    final content = factoryCount == 0
        ? _generateEmptyContent()
        : _generateCodeContent(packages);

    // Write file
    outputFile.writeAsStringSync(content);

    return RegistrationResult(
      outputPath: outputPath,
      packageCount: packages.length,
      factoryCount: factoryCount,
      hasGenerated: factoryCount > 0,
    );
  }

  /// Generates the Dart code content for the registration file.
  String _generateCodeContent(List<WebPackageManifest> packages) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED BY fluttron build - DO NOT EDIT');
    buffer.writeln('// fluttron_web_package registrations');
    buffer.writeln();
    buffer.writeln('// ignore_for_file: directives_ordering');
    buffer.writeln();
    buffer.writeln("import 'package:fluttron_ui/fluttron_ui.dart';");
    buffer.writeln();

    // Function signature
    buffer.writeln('/// Registers all Fluttron web package view factories.');
    buffer.writeln('///');
    buffer.writeln('/// This function is auto-generated by the Fluttron CLI.');
    buffer.writeln('/// Call this in your main.dart before runFluttronUi().');
    buffer.writeln('void registerFluttronWebPackages() {');
    for (final package in packages) {
      final packageName = package.packageName ?? 'unknown';
      if (package.viewFactories.isEmpty) {
        continue;
      }

      buffer.writeln('  // $packageName');
      for (final viewFactory in package.viewFactories) {
        buffer.writeln('  FluttronWebViewRegistry.register(');
        buffer.writeln('    const FluttronWebViewRegistration(');
        buffer.writeln("      type: '${_escapeString(viewFactory.type)}',");
        buffer.writeln(
          "      jsFactoryName: '${_escapeString(viewFactory.jsFactoryName)}',",
        );
        buffer.writeln('    ),');
        buffer.writeln('  );');
      }
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generates content for empty registration file (no packages).
  String _generateEmptyContent() {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED BY fluttron build - DO NOT EDIT');
    buffer.writeln('// fluttron_web_package registrations');
    buffer.writeln('//');
    buffer.writeln('// No web packages found. This file is a placeholder.');
    buffer.writeln();
    buffer.writeln('// ignore_for_file: directives_ordering');
    buffer.writeln();
    buffer.writeln("import 'package:fluttron_ui/fluttron_ui.dart';");
    buffer.writeln();

    buffer.writeln('/// Registers all Fluttron web package view factories.');
    buffer.writeln('///');
    buffer.writeln('/// This function is auto-generated by the Fluttron CLI.');
    buffer.writeln('/// Currently no web packages are registered.');
    buffer.writeln('void registerFluttronWebPackages() {');
    buffer.writeln('  // No web packages to register');
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Escapes special characters in a string for use in Dart string literals.
  ///
  /// Only escapes single quotes since type and jsFactoryName follow strict
  /// naming conventions that don't include backslashes.
  String _escapeString(String value) {
    return value.replaceAll("'", r"\'");
  }

  int _countFactories(List<WebPackageManifest> packages) {
    var count = 0;
    for (final package in packages) {
      count += package.viewFactories.length;
    }
    return count;
  }
}
